services:
  web:
    container_name: nginx
    build:
      context: ./requirements/Nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      django:
        condition: service_healthy
    volumes:
      - ./requirements/Nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./pong_project/pong/static:/usr/share/nginx/html/static
      - ./pong_project/media:/usr/share/nginx/html/media
    restart: always
    networks:
      - mynetwork

  django:
    container_name: django
    build:
      context: ./requirements/Django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./pong_project:/app/code
    environment:
      - DEBUG=1
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  db:
    container_name: db
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    networks:
      - mynetwork

volumes:
  postgres_data:
    name: postgres_data
    driver: local
    driver_opts:
      type: none
      device: /home/stakimot/data/postgres
      o: bind

networks:
  mynetwork:
