# Generated by Django 3.2.25 on 2025-01-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, default='https://example.com/default-avatar.png', max_length=255, null=True),
        ),
    ]
