# Generated by Django 3.2.25 on 2025-02-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
