# Generated by Django 3.2.25 on 2025-02-10 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pong', '0002_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('friend_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(related_name='friend_groups', to='auth.Group')),
                ('user_permissions', models.ManyToManyField(related_name='friend_user_permissions', to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
