# Generated by Django 3.2.25 on 2025-01-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, default='/static/pong/image/avatar-default.jpg', max_length=255, null=True),
        ),
    ]
