# Generated by Django 3.2.25 on 2025-03-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_friend'),
        ('pong', '0005_gameplayers'),
    ]

    operations = [
    ]
