# Generated by Django 3.2.25 on 2025-02-01 06:41

from django.db import migrations, models
import pong.models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=pong.models.user_avatar_upload_path),
        ),
    ]
