# Generated by Django 3.2.25 on 2025-03-04 05:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0008_user_intra_42_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameOptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ball_count', models.IntegerField(choices=[(1, '1個'), (2, '2個')], default=1)),
                ('ball_speed', models.CharField(choices=[('slow', '遅い'), ('normal', '普通'), ('fast', '速い')], default='normal', max_length=10)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pong.game')),
            ],
        ),
    ]
