services:
  web:
    container_name: nginx
    build:
      context: ./requirements/Nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      django:
        condition: service_healthy
    volumes:
      - ./requirements/Nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../pong_project/pong/static:/usr/share/nginx/html/static
    restart: always
    networks:
      - mynetwork

  django:
    container_name: django
    build:
      context: ./requirements/Django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../pong_project:/app/code
    environment:
      - DEBUG=1
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: pong_db
      POSTGRES_USER: pong_user
      POSTGRES_PASSWORD: pong_user_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
