services:
  web:
    container_name: web
    build:
      context: ./requirements/Nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - django
    volumes:
      - ./requirements/Nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

  django:
    container_name: django
    build:
      context: ./requirements/Django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../pong:/app/code
    environment:
      - DEBUG=1
    restart: always